### PR TITLE
scala-ts-mode properly recognizes line comments as comment syntax

### LINKED ISSUE #17: Comment starting position is not correctlty detected
`(nth 8 (syntax-ppss))` returns nil when point is inside a comment which is not correct, see https://www.gnu.org/software/emacs/manual/html_node/elisp/Parser-State.html

For strings it works fine.

### PR DESCRIPTION
**Pull request by ravenjoad**
This lets Emacs recognize `// line comment` as proper comment syntax, rather than just unformatted text. The behavior of `/* block comments */` is unchanged. 

These syntax-table entries are the same as java-ts-mode's, since both languages use the same comment syntax.

Closes #17.

### CODE REVIEW

**Comment by KaranAhlawat** [comment]
I think it would be good to check the syntax table we have here with https://github.com/hvesalai/emacs-scala-mode and see if we're doing the correct thing for comments. If the two are same for comments, please let me know and I'll merge. Otherwise please fix any discrepencies. Thanks for your contribution!

**Comment by ravenjoad** [comment]
I just checked, and it looks like emacs-scala-mode uses the exact same thing as Java's. I omitted the carriage return character though. I will add that and push.

  * Emacs' built-in C/C++/Java modes: https://github.com/emacs-mirror/emacs/blob/d277123f4bf855f0d055d283a42166f123fa1fde/lisp/progmodes/cc-langs.el#L360-L369
  * Emacs' built-in java-ts-mode: https://github.com/emacs-mirror/emacs/blob/d277123f4bf855f0d055d283a42166f123fa1fde/lisp/progmodes/java-ts-mode.el#L66-L69
  * Scala-mode (No TS): https://github.com/hvesalai/emacs-scala-mode/blob/bd0638c32ab0f2eadacf2809329abf5388211760/scala-mode-syntax.el#L494-L499

**Comment by KaranAhlawat** [comment]
It also looks like scala-mode (no TS) allows for nested multi-line comments, [here](https://github.com/hvesalai/emacs-scala-mode/blob/bd0638c32ab0f2eadacf2809329abf5388211760/scala-mode-syntax.el#L495) , could you take a look at that?

**Comment by ravenjoad** [comment]
From just a quick test, this change (without `n`) also handled nested multi-line comments.

```scala
sealed trait Test {
  // TODO: This is a quick note
  // Another
  /* The start of a large comment block.
   * Now inside of the comment block, we nest another comment.
   * /* The nested comment that is also
   *  * multi-line! */
   * */
  def foo(): Unit = {}
}

```

Placing point anywhere inside of the comment block, including inside the nested one, and running the following command: `M-: (nth 8 (syntax-ppss))` returns non-`nil`, which means Emacs understands the contents as comments. If you run that same command on the `def` keyword, you will get `nil` back.

I can add `n`, sure.

Not even Emacs' built-in java-ts-mode does not use `n`, so I am not sure how important it really is.
https://github.com/emacs-mirror/emacs/blob/2847106f3b6174f25ab43551f96612209fe951c8/lisp/progmodes/java-ts-mode.el#L66-L69

**Comment by KaranAhlawat** [comment]
Alright, everything looks good to me. Thank you for your patience and contribution!

**Pull request merged**
